import { describe, expect, it } from 'vitest';

import { objectFromKeys } from '../objectFromKeys.ts';

describe(objectFromKeys, () => {
  describe('with value', () => {
    it('returns an object with the keys and the value', () => {
      const keys = ['a', 'b', 'c'];
      const value = 1;
      const expected = { a: value, b: value, c: value };

      expect(objectFromKeys(keys, value)).toStrictEqual(expected);
    });
  });

  describe('with value function', () => {
    it('returns an object with the keys and the values generated by the function', () => {
      const keys = ['a', 'ab', 'abc'];
      const generateValue = (key: string) => key.length;
      const expected = { a: 1, ab: 2, abc: 3 };

      expect(objectFromKeys(keys, generateValue)).toStrictEqual(expected);
    });

    it('passes the key, index, and array to the value function', () => {
      const keys = ['a', 'b', 'c'];
      const generateValue = (key: string, index: number, array: ReadonlyArray<string>) => {
        return `${key}: ${index + 1}/${array.length}`;
      };
      const expected = { a: 'a: 1/3', b: 'b: 2/3', c: 'c: 3/3' };

      expect(objectFromKeys(keys, generateValue)).toStrictEqual(expected);
    });
  });

  it('can handle keys of different types that extend the string', () => {
    type KeyType = 'a' | 'b' | 'c';
    const keys: KeyType[] = ['a', 'b', 'c'];
    const generateValue = (key: KeyType, index: number) => `${key} ${index}`;
    const expected = { a: 'a 0', b: 'b 1', c: 'c 2' };

    const result = objectFromKeys(keys, generateValue);

    expect(result).toStrictEqual(expected);
  });
});
