# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Code quality checks

on:
  push:
    branches:
      - main
      - next

  pull_request:
    branches:
      - main
      - next

  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  code-quality:
    uses: williamthorsen/.github/.github/workflows/code-quality-pnpm-workflow.yaml@v7
    with:
      check-command: pnpm exec nmr ci
